/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/20220120/GetDepartureBoard/{crs}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["_20220120_GetDepartureBoard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/20220120/GetArrivalBoard/{crs}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["_20220120_GetArrivalBoard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/20220120/GetArrivalDepartureBoard/{crs}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["_20220120_GetArrivalDepartureBoard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/20220120/GetArrBoardWithDetails/{crs}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["_20220120_GetArrBoardWithDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/20220120/GetDepBoardWithDetails/{crs}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["_20220120_GetDepBoardWithDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/20220120/GetArrDepBoardWithDetails/{crs}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["_20220120_GetArrDepBoardWithDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/20220120/GetFastestDepartures/{crs}/{filterList}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["_20220120_GetFastestDepartures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/20220120/GetFastestDeparturesWithDetails/{crs}/{filterList}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["_20220120_GetFastestDeparturesWithDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/20220120/GetNextDepartures/{crs}/{filterList}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["_20220120_GetNextDepartures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/20220120/GetNextDeparturesWithDetails/{crs}/{filterList}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["_20220120_GetNextDeparturesWithDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/20220120/GetServiceDetails/{serviceid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["_20220120_GetServiceDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        StationBoard: {
            trainServices?: components["schemas"]["ServiceItem"][];
            busServices?: components["schemas"]["ServiceItem"][];
            ferryServices?: components["schemas"]["ServiceItem"][];
            Xmlns?: components["schemas"]["XmlSerializerNamespaces"];
            /** Format: date-time */
            generatedAt?: string;
            locationName?: string;
            crs?: string;
            filterLocationName?: string;
            filtercrs?: string;
            /** @enum {string} */
            filterType?: "to" | "from";
            nrccMessages?: components["schemas"]["NRCCMessage"][];
            platformAvailable?: boolean;
            areServicesAvailable?: boolean;
        };
        ServiceItem: {
            formation?: components["schemas"]["FormationData"];
            origin?: components["schemas"]["ServiceLocation"][];
            destination?: components["schemas"]["ServiceLocation"][];
            currentOrigins?: components["schemas"]["ServiceLocation"][];
            currentDestinations?: components["schemas"]["ServiceLocation"][];
            rsid?: string;
            sta?: string;
            eta?: string;
            std?: string;
            etd?: string;
            platform?: string;
            operator?: string;
            operatorCode?: string;
            isCircularRoute?: boolean;
            isCancelled?: boolean;
            filterLocationCancelled?: boolean;
            /** @enum {string} */
            serviceType?: "train" | "bus" | "ferry";
            /** Format: int32 */
            length?: number;
            detachFront?: boolean;
            isReverseFormation?: boolean;
            cancelReason?: string;
            delayReason?: string;
            serviceID?: string;
            adhocAlerts?: string[];
        };
        XmlSerializerNamespaces: {
            /** Format: int32 */
            readonly Count?: number;
        };
        NRCCMessage: {
            Value?: string;
        };
        FormationData: {
            loadingCategory?: components["schemas"]["LoadingCategory"];
            coaches?: components["schemas"]["CoachData"][];
        };
        ServiceLocation: {
            locationName?: string;
            crs?: string;
            via?: string;
            futureChangeTo?: string;
            assocIsCancelled?: boolean;
        };
        LoadingCategory: {
            code?: string;
            colour?: string;
            image?: string;
            Value?: string;
        };
        CoachData: {
            coachClass?: string;
            toilet?: components["schemas"]["ToiletAvailabilityType"];
            /** Format: int32 */
            loading?: number;
            loadingSpecified?: boolean;
            number?: string;
        };
        ToiletAvailabilityType: {
            /** @enum {string} */
            status?: "Unknown" | "InService" | "NotInService";
            Value?: string;
        };
        StationBoardWithDetails: {
            trainServices?: components["schemas"]["ServiceItemWithCallingPoints"][];
            busServices?: components["schemas"]["ServiceItemWithCallingPoints"][];
            ferryServices?: components["schemas"]["ServiceItemWithCallingPoints"][];
            Xmlns?: components["schemas"]["XmlSerializerNamespaces"];
            /** Format: date-time */
            generatedAt?: string;
            locationName?: string;
            crs?: string;
            filterLocationName?: string;
            filtercrs?: string;
            /** @enum {string} */
            filterType?: "to" | "from";
            nrccMessages?: components["schemas"]["NRCCMessage"][];
            platformAvailable?: boolean;
            areServicesAvailable?: boolean;
        };
        ServiceItemWithCallingPoints: {
            previousCallingPoints?: components["schemas"]["ArrayOfCallingPoints"][];
            subsequentCallingPoints?: components["schemas"]["ArrayOfCallingPoints"][];
            formation?: components["schemas"]["FormationData"];
            origin?: components["schemas"]["ServiceLocation"][];
            destination?: components["schemas"]["ServiceLocation"][];
            currentOrigins?: components["schemas"]["ServiceLocation"][];
            currentDestinations?: components["schemas"]["ServiceLocation"][];
            rsid?: string;
            sta?: string;
            eta?: string;
            std?: string;
            etd?: string;
            platform?: string;
            operator?: string;
            operatorCode?: string;
            isCircularRoute?: boolean;
            isCancelled?: boolean;
            filterLocationCancelled?: boolean;
            /** @enum {string} */
            serviceType?: "train" | "bus" | "ferry";
            /** Format: int32 */
            length?: number;
            detachFront?: boolean;
            isReverseFormation?: boolean;
            cancelReason?: string;
            delayReason?: string;
            serviceID?: string;
            adhocAlerts?: string[];
        };
        ArrayOfCallingPoints: {
            callingPoint?: components["schemas"]["CallingPoint"][];
            /** @enum {string} */
            serviceType?: "train" | "bus" | "ferry";
            serviceChangeRequired?: boolean;
            assocIsCancelled?: boolean;
        };
        CallingPoint: {
            locationName?: string;
            crs?: string;
            st?: string;
            et?: string;
            at?: string;
            isCancelled?: boolean;
            /** Format: int32 */
            length?: number;
            detachFront?: boolean;
            formation?: components["schemas"]["FormationData"];
            adhocAlerts?: string[];
        };
        DeparturesBoard: {
            departures?: components["schemas"]["DepartureItem"][];
            Xmlns?: components["schemas"]["XmlSerializerNamespaces"];
            /** Format: date-time */
            generatedAt?: string;
            locationName?: string;
            crs?: string;
            filterLocationName?: string;
            filtercrs?: string;
            /** @enum {string} */
            filterType?: "to" | "from";
            nrccMessages?: components["schemas"]["NRCCMessage"][];
            platformAvailable?: boolean;
            areServicesAvailable?: boolean;
        };
        DepartureItem: {
            service?: components["schemas"]["ServiceItem"];
            crs?: string;
        };
        DeparturesBoardWithDetails: {
            departures?: components["schemas"]["DepartureItemWithCallingPoints"][];
            Xmlns?: components["schemas"]["XmlSerializerNamespaces"];
            /** Format: date-time */
            generatedAt?: string;
            locationName?: string;
            crs?: string;
            filterLocationName?: string;
            filtercrs?: string;
            /** @enum {string} */
            filterType?: "to" | "from";
            nrccMessages?: components["schemas"]["NRCCMessage"][];
            platformAvailable?: boolean;
            areServicesAvailable?: boolean;
        };
        DepartureItemWithCallingPoints: {
            service?: components["schemas"]["ServiceItemWithCallingPoints"];
            crs?: string;
        };
        ServiceDetails: {
            adhocAlerts?: string[];
            formation?: components["schemas"]["FormationData"];
            previousCallingPoints?: components["schemas"]["ArrayOfCallingPoints"][];
            subsequentCallingPoints?: components["schemas"]["ArrayOfCallingPoints"][];
            /** Format: date-time */
            generatedAt?: string;
            /** @enum {string} */
            serviceType?: "train" | "bus" | "ferry";
            locationName?: string;
            crs?: string;
            operator?: string;
            operatorCode?: string;
            rsid?: string;
            isCancelled?: boolean;
            cancelReason?: string;
            delayReason?: string;
            overdueMessage?: string;
            /** Format: int32 */
            length?: number;
            detachFront?: boolean;
            isReverseFormation?: boolean;
            platform?: string;
            sta?: string;
            eta?: string;
            ata?: string;
            std?: string;
            etd?: string;
            atd?: string;
            Xmlns?: components["schemas"]["XmlSerializerNamespaces"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    _20220120_GetDepartureBoard: {
        parameters: {
            query?: {
                numRows?: number;
                filterCrs?: string;
                filterType?: "to" | "from";
                timeOffset?: number;
                timeWindow?: number;
            };
            header?: never;
            path: {
                crs: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationBoard"];
                    "text/json": components["schemas"]["StationBoard"];
                    "application/xml": components["schemas"]["StationBoard"];
                    "text/xml": components["schemas"]["StationBoard"];
                };
            };
        };
    };
    _20220120_GetArrivalBoard: {
        parameters: {
            query?: {
                numRows?: number;
                filterCrs?: string;
                filterType?: "to" | "from";
                timeOffset?: number;
                timeWindow?: number;
            };
            header?: never;
            path: {
                crs: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationBoard"];
                    "text/json": components["schemas"]["StationBoard"];
                    "application/xml": components["schemas"]["StationBoard"];
                    "text/xml": components["schemas"]["StationBoard"];
                };
            };
        };
    };
    _20220120_GetArrivalDepartureBoard: {
        parameters: {
            query?: {
                numRows?: number;
                filterCrs?: string;
                filterType?: "to" | "from";
                timeOffset?: number;
                timeWindow?: number;
            };
            header?: never;
            path: {
                crs: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationBoard"];
                    "text/json": components["schemas"]["StationBoard"];
                    "application/xml": components["schemas"]["StationBoard"];
                    "text/xml": components["schemas"]["StationBoard"];
                };
            };
        };
    };
    _20220120_GetArrBoardWithDetails: {
        parameters: {
            query?: {
                numRows?: number;
                filterCrs?: string;
                filterType?: "to" | "from";
                timeOffset?: number;
                timeWindow?: number;
            };
            header?: never;
            path: {
                crs: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationBoardWithDetails"];
                    "text/json": components["schemas"]["StationBoardWithDetails"];
                    "application/xml": components["schemas"]["StationBoardWithDetails"];
                    "text/xml": components["schemas"]["StationBoardWithDetails"];
                };
            };
        };
    };
    _20220120_GetDepBoardWithDetails: {
        parameters: {
            query?: {
                numRows?: number;
                filterCrs?: string;
                filterType?: "to" | "from";
                timeOffset?: number;
                timeWindow?: number;
            };
            header?: never;
            path: {
                crs: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationBoardWithDetails"];
                    "text/json": components["schemas"]["StationBoardWithDetails"];
                    "application/xml": components["schemas"]["StationBoardWithDetails"];
                    "text/xml": components["schemas"]["StationBoardWithDetails"];
                };
            };
        };
    };
    _20220120_GetArrDepBoardWithDetails: {
        parameters: {
            query?: {
                numRows?: number;
                filterCrs?: string;
                filterType?: "to" | "from";
                timeOffset?: number;
                timeWindow?: number;
            };
            header?: never;
            path: {
                crs: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationBoardWithDetails"];
                    "text/json": components["schemas"]["StationBoardWithDetails"];
                    "application/xml": components["schemas"]["StationBoardWithDetails"];
                    "text/xml": components["schemas"]["StationBoardWithDetails"];
                };
            };
        };
    };
    _20220120_GetFastestDepartures: {
        parameters: {
            query?: {
                timeOffset?: number;
                timeWindow?: number;
            };
            header?: never;
            path: {
                crs: string;
                filterList: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeparturesBoard"];
                    "text/json": components["schemas"]["DeparturesBoard"];
                    "application/xml": components["schemas"]["DeparturesBoard"];
                    "text/xml": components["schemas"]["DeparturesBoard"];
                };
            };
        };
    };
    _20220120_GetFastestDeparturesWithDetails: {
        parameters: {
            query?: {
                timeOffset?: number;
                timeWindow?: number;
            };
            header?: never;
            path: {
                crs: string;
                filterList: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeparturesBoardWithDetails"];
                    "text/json": components["schemas"]["DeparturesBoardWithDetails"];
                    "application/xml": components["schemas"]["DeparturesBoardWithDetails"];
                    "text/xml": components["schemas"]["DeparturesBoardWithDetails"];
                };
            };
        };
    };
    _20220120_GetNextDepartures: {
        parameters: {
            query?: {
                timeOffset?: number;
                timeWindow?: number;
            };
            header?: never;
            path: {
                crs: string;
                filterList: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeparturesBoard"];
                    "text/json": components["schemas"]["DeparturesBoard"];
                    "application/xml": components["schemas"]["DeparturesBoard"];
                    "text/xml": components["schemas"]["DeparturesBoard"];
                };
            };
        };
    };
    _20220120_GetNextDeparturesWithDetails: {
        parameters: {
            query?: {
                timeOffset?: number;
                timeWindow?: number;
            };
            header?: never;
            path: {
                crs: string;
                filterList: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeparturesBoardWithDetails"];
                    "text/json": components["schemas"]["DeparturesBoardWithDetails"];
                    "application/xml": components["schemas"]["DeparturesBoardWithDetails"];
                    "text/xml": components["schemas"]["DeparturesBoardWithDetails"];
                };
            };
        };
    };
    _20220120_GetServiceDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serviceid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceDetails"];
                    "text/json": components["schemas"]["ServiceDetails"];
                    "application/xml": components["schemas"]["ServiceDetails"];
                    "text/xml": components["schemas"]["ServiceDetails"];
                };
            };
        };
    };
}
