---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
    push:
        paths-ignore:
            - "package.json"
            - "yarn.lock"
            - "package-lock.json"
    pull_request:
        paths-ignore:
            - "package.json"
            - "yarn.lock"
            - "package-lock.json"

###############
# Set the Job #
###############
jobs:
    build:
        # Name the Job
        name: Lint Code Base
        # Set the agent to run on
        runs-on: ubuntu-latest

        ##################
        # Load all steps #
        ##################
        steps:
            ##########################
            # Checkout the code base #
            ##########################
            - name: Checkout Code
              uses: actions/checkout@v2
              with:
                  # Full git history is needed to get a proper list of changed files within `super-linter`
                  fetch-depth: 0

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: "14"
            - run: npm install

            ################################
            # Run Linter against code base #
            ################################
            - name: Lint Code Base
              uses: github/super-linter@v3
              env:
                  VALIDATE_ALL_CODEBASE: false
                  DEFAULT_BRANCH: main
                  VALIDATE_JAVASCRIPT_STANDARD: false
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  LINTER_RULES_PATH: .
                  MARKDOWN_CONFIG_FILE: .markdownlint.yml
